services:
  efb:
    image: efb:v3.0.0
    container_name: efb
    volumes:
      - .:/data
      - "./comwechat/Files/:/comwechat/Files/"
      - "./cleanup.sh:/etc/periodic/daily/cleanup.sh"
    restart: unless-stopped
    network_mode: "service:comwechat"
    environment:
      - EFB_PROFILE=comwechat
    logging:
      driver: json-file
      options:
        max-size: 1m

  comwechat:
    container_name: comwechat
    environment:
        - VNCPASS=jiz4oh
        - COMWECHAT_API_PORT=18888
        - COMWECHAT_BRIDGE_SNAPSHOT_NAME=comwechat
        - COMWECHAT_BRIDGE_SNAPSHOT_DIR=/runtime-host/.comwechat-snapshots
    volumes:
        - comwechat_wine:/home/user/.wine/
        - "./comwechat.zip:/runtime-host/comwechat.zip:ro"
        - "./.comwechat-snapshots/:/runtime-host/.comwechat-snapshots/"
        - "./comwechat/Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
        # - "./comwechat/Data/:/home/user/.wine/drive_c/users/user/Application Data/"
    ports:
      - 5905:5905
    command: /run.py
    privileged: true
    network_mode: bridge
    mac_address: "02:42:ac:11:00:21"
    hostname: efb
    restart: unless-stopped
    image: ghcr.io/jiz4oh/docker-comwechat@sha256:0fea5dec609173b8df21843fc349ab7d43f6a067e2ede057ccfeed605dacf786

  efb2:
    image: ghcr.io/jiz4oh/efb:v2.8.0
    container_name: efb2
    volumes:
      - .:/data
      - "./comwechat/efb2/Files/:/comwechat/Files/"
      - "./cleanup.sh:/etc/periodic/daily/cleanup.sh"
    restart: unless-stopped
    network_mode: "service:comwechat2"
    environment:
      - EFB_PROFILE=comwechat2
    logging:
      driver: json-file
      options:
        max-size: 1m

  comwechat2:
    container_name: comwechat2
    environment:
        - VNCPASS=jiz4oh
        - COMWECHAT_API_PORT=18888
        - COMWECHAT_BRIDGE_SNAPSHOT_NAME=comwechat2
        - COMWECHAT_BRIDGE_SNAPSHOT_DIR=/runtime-host/.comwechat-snapshots
    volumes:
        - comwechat2_wine:/home/user/.wine/
        - "./comwechat.zip:/runtime-host/comwechat.zip:ro"
        - "./.comwechat-snapshots/:/runtime-host/.comwechat-snapshots/"
        - "./comwechat/efb2/Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
        # - "./comwechat/Data/:/home/user/.wine/drive_c/users/user/Application Data/"
    ports:
      - 5906:5905
    command: /run.py
    privileged: true
    network_mode: bridge
    mac_address: "02:42:ac:11:00:22"
    hostname: efb2
    restart: unless-stopped
    image: ghcr.io/jiz4oh/docker-comwechat@sha256:0fea5dec609173b8df21843fc349ab7d43f6a067e2ede057ccfeed605dacf786

volumes:
  comwechat_wine:
  comwechat2_wine:
